export type iconName =
"add-circle" |
"add" |
"airplane" |
"alarm" |
"albums" |
"alert-circle" |
"alert" |
"american-football" |
"analytics" |
"aperture" |
"apps" |
"archive" |
"arrow-back-circle" |
"arrow-back" |
"arrow-down-circle" |
"arrow-down" |
"arrow-forward-circle" |
"arrow-forward" |
"arrow-redo-circle" |
"arrow-redo" |
"arrow-undo-circle" |
"arrow-undo" |
"arrow-up-circle" |
"arrow-up" |
"at-circle" |
"at" |
"attach" |
"backspace" |
"bandage" |
"bar-chart" |
"barbell" |
"barcode" |
"baseball" |
"basket" |
"basketball" |
"battery-charging" |
"battery-dead" |
"battery-full" |
"battery-half" |
"beaker" |
"bed" |
"beer" |
"bicycle" |
"bluetooth" |
"boat" |
"body" |
"bonfire" |
"book" |
"bookmark" |
"bookmarks" |
"briefcase" |
"browsers" |
"brush" |
"bug" |
"build" |
"bulb" |
"bus" |
"business" |
"cafe" |
"calculator" |
"calendar" |
"call" |
"camera" |
"camera-reverse" |
"car" |
"car-sport" |
"card" |
"caret-back-circle" |
"caret-back" |
"caret-down-circle" |
"caret-down" |
"caret-forward-circle" |
"caret-forward" |
"caret-up-circle" |
"caret-up" |
"cart" |
"cash" |
"cellular" |
"chatbox-ellipses" |
"chatbox" |
"chatbubble-ellipses" |
"chatbubble" |
"chatbubbles" |
"checkbox" |
"checkmark-circle" |
"checkmark-done-circle" |
"checkmark-done" |
"checkmark" |
"chevron-back-circle" |
"chevron-back" |
"chevron-down-circle" |
"chevron-down" |
"chevron-forward-circle" |
"chevron-forward" |
"chevron-up-circle" |
"chevron-up" |
"clipboard" |
"close-circle" |
"close" |
"cloud-circle" |
"cloud-done" |
"cloud-download" |
"cloud-offline" |
"cloud" |
"cloud-upload" |
"cloudy-night" |
"cloudy" |
"code-download" |
"code" |
"code-slash" |
"code-working" |
"cog" |
"color-fill" |
"color-filter" |
"color-palette" |
"color-wand" |
"compass" |
"construct" |
"contract" |
"contrast" |
"copy" |
"create" |
"crop" |
"cube" |
"cut" |
"desktop" |
"disc" |
"document-attach" |
"document" |
"document-text" |
"documents" |
"download" |
"duplicate" |
"ear" |
"earth" |
"easel" |
"egg" |
"ellipse" |
"ellipsis-horizontal-circle" |
"ellipsis-horizontal" |
"ellipsis-vertical-circle" |
"ellipsis-vertical" |
"enter" |
"exit" |
"expand" |
"eye-off" |
"eye" |
"eyedrop" |
"fast-food" |
"female" |
"file-tray-full" |
"file-tray" |
"file-tray-stacked" |
"film" |
"filter" |
"finger-print" |
"fitness" |
"flag" |
"flame" |
"flash-off" |
"flash" |
"flashlight" |
"flask" |
"flower" |
"folder-open" |
"folder" |
"football" |
"funnel" |
"game-controller" |
"gift" |
"git-branch" |
"git-commit" |
"git-compare" |
"git-merge" |
"git-network" |
"git-pull-request" |
"glasses" |
"globe" |
"golf" |
"grid" |
"hammer" |
"hand-left" |
"hand-right" |
"happy" |
"hardware-chip" |
"headset" |
"heart-circle" |
"heart-dislike-circle" |
"heart-dislike" |
"heart-half" |
"heart" |
"help-buoy" |
"help-circle" |
"help" |
"home" |
"hourglass" |
"ice-cream" |
"image" |
"images" |
"infinite" |
"information-circle" |
"information" |
"journal" |
"key" |
"keypad" |
"language" |
"laptop" |
"layers" |
"leaf" |
"library" |
"link" |
"list-circle" |
"list" |
"locate" |
"location" |
"lock-closed" |
"lock-open" |
"log-in" |
"log-out" |
"magnet" |
"mail-open" |
"mail" |
"mail-unread" |
"male-female" |
"male" |
"man" |
"map" |
"medal" |
"medical" |
"medkit" |
"megaphone" |
"menu" |
"mic-circle" |
"mic-off-circle" |
"mic-off" |
"mic" |
"moon" |
"move" |
"musical-note" |
"musical-notes" |
"navigate-circle" |
"navigate" |
"newspaper" |
"notifications-circle" |
"notifications-off-circle" |
"notifications-off" |
"notifications" |
"nuclear" |
"nutrition" |
"open" |
"options" |
"paper-plane" |
"partly-sunny" |
"pause-circle" |
"pause" |
"paw" |
"pencil" |
"people-circle" |
"people" |
"person-add" |
"person-circle" |
"person" |
"person-remove" |
"phone-landscape" |
"phone-portrait" |
"pie-chart" |
"pin" |
"pint" |
"pizza" |
"planet" |
"play-back-circle" |
"play-back" |
"play-circle" |
"play-forward-circle" |
"play-forward" |
"play" |
"play-skip-back-circle" |
"play-skip-back" |
"play-skip-forward-circle" |
"play-skip-forward" |
"podium" |
"power" |
"pricetag" |
"pricetags" |
"print" |
"pulse" |
"push" |
"qr-code" |
"radio-button-off" |
"radio-button-on" |
"radio" |
"rainy" |
"reader" |
"receipt" |
"recording" |
"refresh-circle" |
"refresh" |
"reload-circle" |
"reload" |
"remove-circle" |
"remove" |
"reorder-four" |
"reorder-three" |
"reorder-two" |
"repeat" |
"resize" |
"restaurant" |
"return-down-back" |
"return-down-forward" |
"return-up-back" |
"return-up-forward" |
"ribbon" |
"rocket" |
"rose" |
"sad" |
"save" |
"scan-circle" |
"scan" |
"school" |
"search-circle" |
"search" |
"send" |
"server" |
"settings" |
"shapes" |
"share" |
"share-social" |
"shield-checkmark" |
"shield" |
"shirt" |
"shuffle" |
"skull" |
"snow" |
"speedometer" |
"square" |
"star-half" |
"star" |
"stats-chart" |
"stop-circle" |
"stop" |
"stopwatch" |
"subway" |
"sunny" |
"swap-horizontal" |
"swap-vertical" |
"sync-circle" |
"sync" |
"tablet-landscape" |
"tablet-portrait" |
"tennisball" |
"terminal" |
"text" |
"thermometer" |
"thumbs-down" |
"thumbs-up" |
"thunderstorm" |
"time" |
"timer" |
"today" |
"toggle" |
"trail-sign" |
"train" |
"transgender" |
"trash-bin" |
"trash" |
"trending-down" |
"trending-up" |
"triangle" |
"trophy" |
"tv" |
"umbrella" |
"videocam" |
"volume-high" |
"volume-low" |
"volume-medium" |
"volume-mute" |
"volume-off" |
"walk" |
"wallet" |
"warning" |
"watch" |
"water" |
"wifi" |
"wine" |
"woman" |
"ios-add-circle" |
"ios-add" |
"ios-airplane" |
"ios-alarm" |
"ios-albums" |
"ios-alert-circle" |
"ios-alert" |
"ios-american-football" |
"ios-analytics" |
"ios-aperture" |
"ios-apps" |
"ios-archive" |
"ios-arrow-back-circle" |
"ios-arrow-back" |
"ios-arrow-down-circle" |
"ios-arrow-down" |
"ios-arrow-forward-circle" |
"ios-arrow-forward" |
"ios-arrow-redo-circle" |
"ios-arrow-redo" |
"ios-arrow-undo-circle" |
"ios-arrow-undo" |
"ios-arrow-up-circle" |
"ios-arrow-up" |
"ios-at-circle" |
"ios-at" |
"ios-attach" |
"ios-backspace" |
"ios-bandage" |
"ios-bar-chart" |
"ios-barbell" |
"ios-barcode" |
"ios-baseball" |
"ios-basket" |
"ios-basketball" |
"ios-battery-charging" |
"ios-battery-dead" |
"ios-battery-full" |
"ios-battery-half" |
"ios-beaker" |
"ios-bed" |
"ios-beer" |
"ios-bicycle" |
"ios-bluetooth" |
"ios-boat" |
"ios-body" |
"ios-bonfire" |
"ios-book" |
"ios-bookmark" |
"ios-bookmarks" |
"ios-briefcase" |
"ios-browsers" |
"ios-brush" |
"ios-bug" |
"ios-build" |
"ios-bulb" |
"ios-bus" |
"ios-business" |
"ios-cafe" |
"ios-calculator" |
"ios-calendar" |
"ios-call" |
"ios-camera" |
"ios-camera-reverse" |
"ios-car" |
"ios-car-sport" |
"ios-card" |
"ios-caret-back-circle" |
"ios-caret-back" |
"ios-caret-down-circle" |
"ios-caret-down" |
"ios-caret-forward-circle" |
"ios-caret-forward" |
"ios-caret-up-circle" |
"ios-caret-up" |
"ios-cart" |
"ios-cash" |
"ios-cellular" |
"ios-chatbox-ellipses" |
"ios-chatbox" |
"ios-chatbubble-ellipses" |
"ios-chatbubble" |
"ios-chatbubbles" |
"ios-checkbox" |
"ios-checkmark-circle" |
"ios-checkmark-done-circle" |
"ios-checkmark-done" |
"ios-checkmark" |
"ios-chevron-back-circle" |
"ios-chevron-back" |
"ios-chevron-down-circle" |
"ios-chevron-down" |
"ios-chevron-forward-circle" |
"ios-chevron-forward" |
"ios-chevron-up-circle" |
"ios-chevron-up" |
"ios-clipboard" |
"ios-close-circle" |
"ios-close" |
"ios-cloud-circle" |
"ios-cloud-done" |
"ios-cloud-download" |
"ios-cloud-offline" |
"ios-cloud" |
"ios-cloud-upload" |
"ios-cloudy-night" |
"ios-cloudy" |
"ios-code-download" |
"ios-code" |
"ios-code-slash" |
"ios-code-working" |
"ios-cog" |
"ios-color-fill" |
"ios-color-filter" |
"ios-color-palette" |
"ios-color-wand" |
"ios-compass" |
"ios-construct" |
"ios-contract" |
"ios-contrast" |
"ios-copy" |
"ios-create" |
"ios-crop" |
"ios-cube" |
"ios-cut" |
"ios-desktop" |
"ios-disc" |
"ios-document-attach" |
"ios-document" |
"ios-document-text" |
"ios-documents" |
"ios-download" |
"ios-duplicate" |
"ios-ear" |
"ios-earth" |
"ios-easel" |
"ios-egg" |
"ios-ellipse" |
"ios-ellipsis-horizontal-circle" |
"ios-ellipsis-horizontal" |
"ios-ellipsis-vertical-circle" |
"ios-ellipsis-vertical" |
"ios-enter" |
"ios-exit" |
"ios-expand" |
"ios-eye-off" |
"ios-eye" |
"ios-eyedrop" |
"ios-fast-food" |
"ios-female" |
"ios-file-tray-full" |
"ios-file-tray" |
"ios-file-tray-stacked" |
"ios-film" |
"ios-filter" |
"ios-finger-print" |
"ios-fitness" |
"ios-flag" |
"ios-flame" |
"ios-flash-off" |
"ios-flash" |
"ios-flashlight" |
"ios-flask" |
"ios-flower" |
"ios-folder-open" |
"ios-folder" |
"ios-football" |
"ios-funnel" |
"ios-game-controller" |
"ios-gift" |
"ios-git-branch" |
"ios-git-commit" |
"ios-git-compare" |
"ios-git-merge" |
"ios-git-network" |
"ios-git-pull-request" |
"ios-glasses" |
"ios-globe" |
"ios-golf" |
"ios-grid" |
"ios-hammer" |
"ios-hand-left" |
"ios-hand-right" |
"ios-happy" |
"ios-hardware-chip" |
"ios-headset" |
"ios-heart-circle" |
"ios-heart-dislike-circle" |
"ios-heart-dislike" |
"ios-heart-half" |
"ios-heart" |
"ios-help-buoy" |
"ios-help-circle" |
"ios-help" |
"ios-home" |
"ios-hourglass" |
"ios-ice-cream" |
"ios-image" |
"ios-images" |
"ios-infinite" |
"ios-information-circle" |
"ios-information" |
"ios-journal" |
"ios-key" |
"ios-keypad" |
"ios-language" |
"ios-laptop" |
"ios-layers" |
"ios-leaf" |
"ios-library" |
"ios-link" |
"ios-list-circle" |
"ios-list" |
"ios-locate" |
"ios-location" |
"ios-lock-closed" |
"ios-lock-open" |
"ios-log-in" |
"ios-log-out" |
"ios-magnet" |
"ios-mail-open" |
"ios-mail" |
"ios-mail-unread" |
"ios-male-female" |
"ios-male" |
"ios-man" |
"ios-map" |
"ios-medal" |
"ios-medical" |
"ios-medkit" |
"ios-megaphone" |
"ios-menu" |
"ios-mic-circle" |
"ios-mic-off-circle" |
"ios-mic-off" |
"ios-mic" |
"ios-moon" |
"ios-move" |
"ios-musical-note" |
"ios-musical-notes" |
"ios-navigate-circle" |
"ios-navigate" |
"ios-newspaper" |
"ios-notifications-circle" |
"ios-notifications-off-circle" |
"ios-notifications-off" |
"ios-notifications" |
"ios-nuclear" |
"ios-nutrition" |
"ios-open" |
"ios-options" |
"ios-paper-plane" |
"ios-partly-sunny" |
"ios-pause-circle" |
"ios-pause" |
"ios-paw" |
"ios-pencil" |
"ios-people-circle" |
"ios-people" |
"ios-person-add" |
"ios-person-circle" |
"ios-person" |
"ios-person-remove" |
"ios-phone-landscape" |
"ios-phone-portrait" |
"ios-pie-chart" |
"ios-pin" |
"ios-pint" |
"ios-pizza" |
"ios-planet" |
"ios-play-back-circle" |
"ios-play-back" |
"ios-play-circle" |
"ios-play-forward-circle" |
"ios-play-forward" |
"ios-play" |
"ios-play-skip-back-circle" |
"ios-play-skip-back" |
"ios-play-skip-forward-circle" |
"ios-play-skip-forward" |
"ios-podium" |
"ios-power" |
"ios-pricetag" |
"ios-pricetags" |
"ios-print" |
"ios-pulse" |
"ios-push" |
"ios-qr-code" |
"ios-radio-button-off" |
"ios-radio-button-on" |
"ios-radio" |
"ios-rainy" |
"ios-reader" |
"ios-receipt" |
"ios-recording" |
"ios-refresh-circle" |
"ios-refresh" |
"ios-reload-circle" |
"ios-reload" |
"ios-remove-circle" |
"ios-remove" |
"ios-reorder-four" |
"ios-reorder-three" |
"ios-reorder-two" |
"ios-repeat" |
"ios-resize" |
"ios-restaurant" |
"ios-return-down-back" |
"ios-return-down-forward" |
"ios-return-up-back" |
"ios-return-up-forward" |
"ios-ribbon" |
"ios-rocket" |
"ios-rose" |
"ios-sad" |
"ios-save" |
"ios-scan-circle" |
"ios-scan" |
"ios-school" |
"ios-search-circle" |
"ios-search" |
"ios-send" |
"ios-server" |
"ios-settings" |
"ios-shapes" |
"ios-share" |
"ios-share-social" |
"ios-shield-checkmark" |
"ios-shield" |
"ios-shirt" |
"ios-shuffle" |
"ios-skull" |
"ios-snow" |
"ios-speedometer" |
"ios-square" |
"ios-star-half" |
"ios-star" |
"ios-stats-chart" |
"ios-stop-circle" |
"ios-stop" |
"ios-stopwatch" |
"ios-subway" |
"ios-sunny" |
"ios-swap-horizontal" |
"ios-swap-vertical" |
"ios-sync-circle" |
"ios-sync" |
"ios-tablet-landscape" |
"ios-tablet-portrait" |
"ios-tennisball" |
"ios-terminal" |
"ios-text" |
"ios-thermometer" |
"ios-thumbs-down" |
"ios-thumbs-up" |
"ios-thunderstorm" |
"ios-time" |
"ios-timer" |
"ios-today" |
"ios-toggle" |
"ios-trail-sign" |
"ios-train" |
"ios-transgender" |
"ios-trash-bin" |
"ios-trash" |
"ios-trending-down" |
"ios-trending-up" |
"ios-triangle" |
"ios-trophy" |
"ios-tv" |
"ios-umbrella" |
"ios-videocam" |
"ios-volume-high" |
"ios-volume-low" |
"ios-volume-medium" |
"ios-volume-mute" |
"ios-volume-off" |
"ios-walk" |
"ios-wallet" |
"ios-warning" |
"ios-watch" |
"ios-water" |
"ios-wifi" |
"ios-wine" |
"ios-woman" |
"md-add-circle" |
"md-add" |
"md-airplane" |
"md-alarm" |
"md-albums" |
"md-alert-circle" |
"md-alert" |
"md-american-football" |
"md-analytics" |
"md-aperture" |
"md-apps" |
"md-archive" |
"md-arrow-back-circle" |
"md-arrow-back" |
"md-arrow-down-circle" |
"md-arrow-down" |
"md-arrow-forward-circle" |
"md-arrow-forward" |
"md-arrow-redo-circle" |
"md-arrow-redo" |
"md-arrow-undo-circle" |
"md-arrow-undo" |
"md-arrow-up-circle" |
"md-arrow-up" |
"md-at-circle" |
"md-at" |
"md-attach" |
"md-backspace" |
"md-bandage" |
"md-bar-chart" |
"md-barbell" |
"md-barcode" |
"md-baseball" |
"md-basket" |
"md-basketball" |
"md-battery-charging" |
"md-battery-dead" |
"md-battery-full" |
"md-battery-half" |
"md-beaker" |
"md-bed" |
"md-beer" |
"md-bicycle" |
"md-bluetooth" |
"md-boat" |
"md-body" |
"md-bonfire" |
"md-book" |
"md-bookmark" |
"md-bookmarks" |
"md-briefcase" |
"md-browsers" |
"md-brush" |
"md-bug" |
"md-build" |
"md-bulb" |
"md-bus" |
"md-business" |
"md-cafe" |
"md-calculator" |
"md-calendar" |
"md-call" |
"md-camera" |
"md-camera-reverse" |
"md-car" |
"md-car-sport" |
"md-card" |
"md-caret-back-circle" |
"md-caret-back" |
"md-caret-down-circle" |
"md-caret-down" |
"md-caret-forward-circle" |
"md-caret-forward" |
"md-caret-up-circle" |
"md-caret-up" |
"md-cart" |
"md-cash" |
"md-cellular" |
"md-chatbox-ellipses" |
"md-chatbox" |
"md-chatbubble-ellipses" |
"md-chatbubble" |
"md-chatbubbles" |
"md-checkbox" |
"md-checkmark-circle" |
"md-checkmark-done-circle" |
"md-checkmark-done" |
"md-checkmark" |
"md-chevron-back-circle" |
"md-chevron-back" |
"md-chevron-down-circle" |
"md-chevron-down" |
"md-chevron-forward-circle" |
"md-chevron-forward" |
"md-chevron-up-circle" |
"md-chevron-up" |
"md-clipboard" |
"md-close-circle" |
"md-close" |
"md-cloud-circle" |
"md-cloud-done" |
"md-cloud-download" |
"md-cloud-offline" |
"md-cloud" |
"md-cloud-upload" |
"md-cloudy-night" |
"md-cloudy" |
"md-code-download" |
"md-code" |
"md-code-slash" |
"md-code-working" |
"md-cog" |
"md-color-fill" |
"md-color-filter" |
"md-color-palette" |
"md-color-wand" |
"md-compass" |
"md-construct" |
"md-contract" |
"md-contrast" |
"md-copy" |
"md-create" |
"md-crop" |
"md-cube" |
"md-cut" |
"md-desktop" |
"md-disc" |
"md-document-attach" |
"md-document" |
"md-document-text" |
"md-documents" |
"md-download" |
"md-duplicate" |
"md-ear" |
"md-earth" |
"md-easel" |
"md-egg" |
"md-ellipse" |
"md-ellipsis-horizontal-circle" |
"md-ellipsis-horizontal" |
"md-ellipsis-vertical-circle" |
"md-ellipsis-vertical" |
"md-enter" |
"md-exit" |
"md-expand" |
"md-eye-off" |
"md-eye" |
"md-eyedrop" |
"md-fast-food" |
"md-female" |
"md-file-tray-full" |
"md-file-tray" |
"md-file-tray-stacked" |
"md-film" |
"md-filter" |
"md-finger-print" |
"md-fitness" |
"md-flag" |
"md-flame" |
"md-flash-off" |
"md-flash" |
"md-flashlight" |
"md-flask" |
"md-flower" |
"md-folder-open" |
"md-folder" |
"md-football" |
"md-funnel" |
"md-game-controller" |
"md-gift" |
"md-git-branch" |
"md-git-commit" |
"md-git-compare" |
"md-git-merge" |
"md-git-network" |
"md-git-pull-request" |
"md-glasses" |
"md-globe" |
"md-golf" |
"md-grid" |
"md-hammer" |
"md-hand-left" |
"md-hand-right" |
"md-happy" |
"md-hardware-chip" |
"md-headset" |
"md-heart-circle" |
"md-heart-dislike-circle" |
"md-heart-dislike" |
"md-heart-half" |
"md-heart" |
"md-help-buoy" |
"md-help-circle" |
"md-help" |
"md-home" |
"md-hourglass" |
"md-ice-cream" |
"md-image" |
"md-images" |
"md-infinite" |
"md-information-circle" |
"md-information" |
"md-journal" |
"md-key" |
"md-keypad" |
"md-language" |
"md-laptop" |
"md-layers" |
"md-leaf" |
"md-library" |
"md-link" |
"md-list-circle" |
"md-list" |
"md-locate" |
"md-location" |
"md-lock-closed" |
"md-lock-open" |
"md-log-in" |
"md-log-out" |
"md-magnet" |
"md-mail-open" |
"md-mail" |
"md-mail-unread" |
"md-male-female" |
"md-male" |
"md-man" |
"md-map" |
"md-medal" |
"md-medical" |
"md-medkit" |
"md-megaphone" |
"md-menu" |
"md-mic-circle" |
"md-mic-off-circle" |
"md-mic-off" |
"md-mic" |
"md-moon" |
"md-move" |
"md-musical-note" |
"md-musical-notes" |
"md-navigate-circle" |
"md-navigate" |
"md-newspaper" |
"md-notifications-circle" |
"md-notifications-off-circle" |
"md-notifications-off" |
"md-notifications" |
"md-nuclear" |
"md-nutrition" |
"md-open" |
"md-options" |
"md-paper-plane" |
"md-partly-sunny" |
"md-pause-circle" |
"md-pause" |
"md-paw" |
"md-pencil" |
"md-people-circle" |
"md-people" |
"md-person-add" |
"md-person-circle" |
"md-person" |
"md-person-remove" |
"md-phone-landscape" |
"md-phone-portrait" |
"md-pie-chart" |
"md-pin" |
"md-pint" |
"md-pizza" |
"md-planet" |
"md-play-back-circle" |
"md-play-back" |
"md-play-circle" |
"md-play-forward-circle" |
"md-play-forward" |
"md-play" |
"md-play-skip-back-circle" |
"md-play-skip-back" |
"md-play-skip-forward-circle" |
"md-play-skip-forward" |
"md-podium" |
"md-power" |
"md-pricetag" |
"md-pricetags" |
"md-print" |
"md-pulse" |
"md-push" |
"md-qr-code" |
"md-radio-button-off" |
"md-radio-button-on" |
"md-radio" |
"md-rainy" |
"md-reader" |
"md-receipt" |
"md-recording" |
"md-refresh-circle" |
"md-refresh" |
"md-reload-circle" |
"md-reload" |
"md-remove-circle" |
"md-remove" |
"md-reorder-four" |
"md-reorder-three" |
"md-reorder-two" |
"md-repeat" |
"md-resize" |
"md-restaurant" |
"md-return-down-back" |
"md-return-down-forward" |
"md-return-up-back" |
"md-return-up-forward" |
"md-ribbon" |
"md-rocket" |
"md-rose" |
"md-sad" |
"md-save" |
"md-scan-circle" |
"md-scan" |
"md-school" |
"md-search-circle" |
"md-search" |
"md-send" |
"md-server" |
"md-settings" |
"md-shapes" |
"md-share" |
"md-share-social" |
"md-shield-checkmark" |
"md-shield" |
"md-shirt" |
"md-shuffle" |
"md-skull" |
"md-snow" |
"md-speedometer" |
"md-square" |
"md-star-half" |
"md-star" |
"md-stats-chart" |
"md-stop-circle" |
"md-stop" |
"md-stopwatch" |
"md-subway" |
"md-sunny" |
"md-swap-horizontal" |
"md-swap-vertical" |
"md-sync-circle" |
"md-sync" |
"md-tablet-landscape" |
"md-tablet-portrait" |
"md-tennisball" |
"md-terminal" |
"md-text" |
"md-thermometer" |
"md-thumbs-down" |
"md-thumbs-up" |
"md-thunderstorm" |
"md-time" |
"md-timer" |
"md-today" |
"md-toggle" |
"md-trail-sign" |
"md-train" |
"md-transgender" |
"md-trash-bin" |
"md-trash" |
"md-trending-down" |
"md-trending-up" |
"md-triangle" |
"md-trophy" |
"md-tv" |
"md-umbrella" |
"md-videocam" |
"md-volume-high" |
"md-volume-low" |
"md-volume-medium" |
"md-volume-mute" |
"md-volume-off" |
"md-walk" |
"md-wallet" |
"md-warning" |
"md-watch" |
"md-water" |
"md-wifi" |
"md-wine" |
"md-woman" 
