export const LOCAL_SCHEDULED_ALERT_WRITE = "local_scheduledAlertWrite";

export const remoteNotificationChannelList = {
  // notice
  NOTICE:"NOTICE",
  // music
  MUSIC_CHANGED:"MUSIC_CHANGED",
  MUSIC_SELECTED:"MUSIC_SELECTED",
  // board
  MY_BOARD_GET_LIKE:"MY_BOARD_GET_LIKE",
  MY_BOARD_GET_COMMENT:"MY_BOARD_GET_COMMENT",
  MY_BOARD_COMMENT_GET_LIKE:"MY_BOARD_COMMENT_GET_LIKE",
  MY_BOARD_COMMENT_GET_COMMENT:"MY_BOARD_COMMENT_GET_COMMENT",
  MY_BOARD_COMMENT_OF_COMMENT_GET_LIKE:"MY_BOARD_COMMENT_OF_COMMENT_GET_LIKE",
};
